### ISSUE TITLE
Solution is not compilable.

### ISSUE THREAD

**Issue by vitalWord** [dan-1992/test_task#1]
1>------ Build started: Project: CppShellExtContextMenuHandler, Configuration: Release x64 ------
1>  ClassFactory.cpp
1>ClassFactory.cpp(2): fatal error C1083: Cannot open include file: 'FileContextMenuExt.h': No such file or directory
1>  FileContextMenuExt.cpp
1>FileContextMenuExt.cpp(1): fatal error C1083: Cannot open include file: 'FileContextMenuExt.h': No such file or directory
1>  Reg.cpp
1>c1xx : fatal error C1083: Cannot open source file: 'Reg.cpp': No such file or directory
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by dan-1992** [comment]
not all files was included in initital commit
fixed
